"""Build fleet-card settlement Journal vouchers by cloning a real exported one.

Each voucher is Dr ``Fleet Card Posting`` / Cr ``<Customer>`` for the amount, so a
customer who paid via XtraPower has their dues cleared against the fleet-card
account. Generating one is surgical, like the IOCL/bank tools:

* strip the identity fields so each imports as a fresh Create and Tally
  auto-numbers it;
* set the date;
* swap the template's customer name for the row's customer (XML-escaped — a bare
  ``&`` makes the file invalid XML and Tally silently drops vouchers);
* replace the amount magnitude, keeping each entry's template sign (Fleet Card
  Posting Dr = negative, customer Cr = positive), so the voucher balances.
"""

from __future__ import annotations

import os
import re

TEMPLATE_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "templates")

FLEET_LEDGER = "Fleet Card Posting"
TDS_LEDGER = "TDS RECEIVABLE - DEBTORS"

# Both entry kinds are the same shape — Dr <posting ledger> / Cr <customer> — so
# each is generated by cloning one real exported voucher and substituting its own
# customer name + amount magnitude. ``ledger`` is just for callers/tests.
KINDS = {
    "fleet": {"file": "FLEET_JOURNAL.xml", "ledger": FLEET_LEDGER,
              "tpl_customer": "Ember Coal Beneficiation Private Limited",
              "tpl_magnitude": "114251.25"},
    "tds":   {"file": "TDS_JOURNAL.xml", "ledger": TDS_LEDGER,
              "tpl_customer": "Orissa Metaliks Private Limited",
              "tpl_magnitude": "1209.00"},
}

_STRIP_TAGS = ["GUID", "ALTERID", "MASTERID", "VOUCHERKEY", "VOUCHERRETAINKEY",
               "VOUCHERNUMBER"]
_DATE_TAGS = ["DATE", "VCHSTATUSDATE", "EFFECTIVEDATE"]


def _read_template(name: str) -> str:
    with open(os.path.join(TEMPLATE_DIR, name), encoding="utf-8") as fh:
        return fh.read()


def _esc(s: str) -> str:
    """XML-escape a substituted value (customer names can contain ``&``)."""
    return s.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def _strip_identity(vch: str) -> str:
    for tag in _STRIP_TAGS:
        vch = re.sub(rf"\s*<{tag}>[^<]*</{tag}>", "", vch)
    vch = re.sub(r'\s+REMOTEID="[^"]*"', "", vch, count=1)
    vch = re.sub(r'\s+VCHKEY="[^"]*"', "", vch, count=1)
    return vch


def _set_dates(vch: str, ymd: str) -> str:
    for tag in _DATE_TAGS:
        vch = re.sub(rf"<{tag}>[^<]*</{tag}>", f"<{tag}>{ymd}</{tag}>", vch)
    return vch


def make_journal(kind: str, ymd: str, customer: str, amount: float) -> str:
    """One settlement journal of ``kind`` ("fleet" or "tds"):
    Dr <posting ledger> / Cr ``customer`` for ``amount``."""
    k = KINDS[kind]
    vch = _strip_identity(_read_template(k["file"]))
    vch = _set_dates(vch, ymd)
    vch = vch.replace(k["tpl_customer"], _esc(customer))
    # Magnitude appears 4x (posting ledger AMOUNT/VATEXP as -, customer as +);
    # the leading '-' on the Dr side is preserved by the literal replace.
    vch = vch.replace(k["tpl_magnitude"], f"{amount:.2f}")
    return vch


def make_fleet_journal(ymd: str, customer: str, amount: float) -> str:
    return make_journal("fleet", ymd, customer, amount)


def make_tds_journal(ymd: str, customer: str, amount: float) -> str:
    return make_journal("tds", ymd, customer, amount)


def voucher_balances(vch: str) -> bool:
    amts = [float(x) for x in re.findall(
        r"<ALLLEDGERENTRIES\.LIST>.*?<AMOUNT>(-?[\d.]+)</AMOUNT>", vch, re.S)]
    return bool(amts) and abs(round(sum(amts), 2)) < 0.005


ENVELOPE_HEAD = (
    "<ENVELOPE>\n <HEADER>\n  <TALLYREQUEST>Import Data</TALLYREQUEST>\n"
    " </HEADER>\n <BODY>\n  <IMPORTDATA>\n   <REQUESTDESC>\n"
    "    <REPORTNAME>Vouchers</REPORTNAME>\n    <STATICVARIABLES>\n"
    "     <SVCURRENTCOMPANY>VRIDDHI FUELS (2026-27)</SVCURRENTCOMPANY>\n"
    "    </STATICVARIABLES>\n   </REQUESTDESC>\n   <REQUESTDATA>\n")
ENVELOPE_TAIL = "   </REQUESTDATA>\n  </IMPORTDATA>\n </BODY>\n</ENVELOPE>\n"


def build_envelope(vouchers: list[str]) -> str:
    body = "\n".join(f"    <TALLYMESSAGE xmlns:UDF=\"TallyUDF\">\n{v}\n    </TALLYMESSAGE>"
                     for v in vouchers)
    return ENVELOPE_HEAD + body + "\n" + ENVELOPE_TAIL
